#!/bin/bash
MAJOR=0
MINOR=0
PATCH=2
VERSION="$MAJOR.$MINOR.$PATCH"

git diff-files --quiet
if [ "$?" != 0 ]; then
    COMMIT="$(git rev-parse --short=10 HEAD)-dirty"
else
    COMMIT="$(git rev-parse --short=10 HEAD)"
fi

