FROM google/golang

MAINTAINER Tyrell Keene <tyrell.wkeene@gmail.com>

RUN useradd -ms /bin/bash autobd
USER autobd

ENV GOPATH=/home/autobd/go

RUN go get github.com/tywkeene/autobd

WORKDIR $GOPATH/src/github.com/tywkeene/autobd/
RUN bash build.sh

RUN mkdir /home/autobd/data
VOLUME /home/autobd/data

EXPOSE 8080
ENTRYPOINT ./autobd -config /home/autobd/etc/config.toml.node
